# 绑定本地代码到容器，定义各项必要服务。

version: "3.7"
services:
  static:
    image: nginx
    volumes:
    - ./static:/usr/share/nginx/static/static
    - ./front:/usr/share/nginx/pipages
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./upload:/usr/share/nginx/upload
    ports:
      - "9001:80"
    depends_on:
      - rest
    restart: always
  # REST API
  rest:
    build: .
    image: pipages
    volumes:
      - .:/opt/pipages
    depends_on:
      - redis
    restart: always
    expose:
      - 8000
    entrypoint:
      - daphne
      - -b
      - 0.0.0.0
      - pipages.asgi:application
  # redis
  redis:
    image: redis
    restart: always
